import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SideBar from "@/components/Drawer";
import GlobalProvider from "./globalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Invoice app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex lg:flex-row`}>
        <GlobalProvider>
          <Navbar />
          <SideBar />
          <main className="sm-container md:max-container md:overflow-y-scroll">
            {children}
          </main>
        </GlobalProvider>
      </body>
    </html>
  );
}
